### ISSUE TITLE
PT-E500 too much whitespace

### ISSUE THREAD

**Issue by johndoc** [HenrikBengtsson/brother-ptouch-label-printer-on-linux#2]
I  have roughly 20-25mm of whitespace before my text starts. I'm a novice at best when it comes to coding, but I've dug through the src/ptouch-print.c and src/libptouch.c and can't seem to find where the change needs to happen.

I do see:

`//offset=64- (gdImageSY(im)/2);`

This is commented out though, correct?

**Comment by HenrikBengtsson** [comment]
This is a FAQ.  It's due to the physical design of these printers and cannot be avoided. I've added a point under the 'Gist' section explaining this. Hope this helps.
