### ISSUE TITLE
Could not find GD library

### ISSUE THREAD

**Issue by manwithakeyboard** [HenrikBengtsson/brother-ptouch-label-printer-on-linux#6]
After running ./build.sh CMake returns

> CMake Error at cmake/FindGD.cmake:109 (MESSAGE):
>   Could not find GD library

despite
Name         : gd
Version      : 2.3.3
already being installed, checked FindGD.cmake and it is looking for it at

> PATHS /usr/lib64 /usr/lib /usr/local/lib

which libgd.so.3 that links to libgd.so.3.0.11 is present (both lib & lib64) in so is it looking for the right library but with the wrong name??

Linux: Fedora 38
Any help appreciated but I understand if you don't have the time.

**Comment by HenrikBengtsson** [comment]
You probably need to install also `gd-devel`. `*-devel` companion packages are needed when you install from source.

**Comment by manwithakeyboard** [comment]
Thanks I also had to use libusb1-devel instead of the already installed libusb1.

**Comment by HenrikBengtsson** [comment]
Good to hear; I've updated <https://github.com/HenrikBengtsson/brother-ptouch-label-printer-on-linux#requirements> with instructions for RedHat/Fedora too.
